### ISSUE TITLE
Zone Control

### ISSUE THREAD

**Issue by tanami20** [TimofeyK/cmd4-Daikin-Airbase#1]
Hi Tim,
Glad you made this module! I have a 4 zone controller. 
From the command line while I am testing I can see :
bash BRP15B61.sh Get Daikin CurrentTemperature

Which returns a degrees. 

What is the command to turn on the Cooling for 1 zone?
I tried:

bash BRP15B61.sh Set Daikin On - it says "ok" but nothing changes.
I'm not good with command line, but how would we go about doing the different zones as in something like
bash BRP15B61.sh Set Daikin Zone 1 On     < Would turn on Zone 1 on

Is something like that possible? I guess then I could add numerious lines to HomeBridge to represent each command line for each zone?

**Comment by TimofeyK** [comment]
https://github.com/TimofeyK/cmd4-Daikin-Airbase/issues/3
