### ISSUE TITLE
Add Function to SET Temperature

### ISSUE THREAD

**Issue by tanami20** [TimofeyK/cmd4-Daikin-Airbase#2]
Hi Tim,

You did an amazing job with the module. It works with my Homekit to turn on/off and read existing fan and temperature. 

I would like to see what we can do to SET the temperature, and set the range for homekit to work between?

**Comment by TimofeyK** [comment]
This script already sets the target temperature. In Home app you need to turn a cooling or heating mode first, then you can adjust the temperature
